### PR TITLE
Add batched dgemm to CCSD(T) for openmp offload and openacc implementations

### PR DESCRIPTION
**Pull request by omarkahmed**
This is an implementation of Batched DGEMM for CCSD(T) for OpenMP Offload and OpenACC implementations.

Acknowledgements include:
Nawal Copty
Rakesh Krishnaiyer
Abhinav Gaba
Ravi Narayanaswamy
Nitin Gawande

### CODE REVIEW

**Comment by edoapra** [comment]
@omarkahmed could you please rebase your pull request to the current master?

**Comment by omarkahmed** [comment]
@edoapra , just rebased.

**Comment by edoapra** [comment]
@omarkahmed This comment is on the previous commit 05f5cb5cfb4284955ac2f12365c4d851e714db40  you made 8 months ago

Why did you put options for the C compiler when the ccsd compiler does not contain any C source code?
https://github.com/nwchemgit/nwchem/blame/80cff689dbd18943911ee13cc7f4b8a305f52445/src/ccsd/GNUmakefile#L133-L137

**Comment by omarkahmed** [comment]
> @omarkahmed This comment is about the previous commit [05f5cb5](https://github.com/nwchemgit/nwchem/commit/05f5cb5cfb4284955ac2f12365c4d851e714db40) you made 8 months ago
> 
> Why did you put options for the C compiler when the ccsd compiler does not contain any C source code? https://github.com/nwchemgit/nwchem/blame/80cff689dbd18943911ee13cc7f4b8a305f52445/src/ccsd/GNUmakefile#L133-L137

Thanks, that's a good point.  This was due to earlier versions which had some C source.  Currently sanity checking that removing this code doesn't impact my unit tests.

**Comment by edoapra** [comment]
I think that the Fortran options might need some cleanup, too.
For example, I see some MKL related bits. Are those needed at compile time or link time?

**Comment by jeffhammond** [comment]
The "OpenACC" version uses CUDA Fortran and only compiles with NVHPC Fortran. I didn't bother renaming it but it really should just be the "nvhpc" or "Nvidia" version.

If you added batched CUBLAS, I'll take a look, but the dimensions used in CCSD(T) are known to not leverage batching effectively. The current version with async streams splits the batch of GEMMs so adding one batched call is more synchronous. It's unlikely to be better on any NVIDIA GPU, which is the only supported hardware for the code as written.

**Comment by omarkahmed** [comment]
> I think that the Fortran options might need some cleanup, too. For example, I see some MKL related bits. Are those needed at compile time or link time?

@edoapra , thanks for the suggestion!  I just pushed up a patch to separate out the INCLUDES and DEFINES.

> The "OpenACC" version uses CUDA Fortran and only compiles with NVHPC Fortran. I didn't bother renaming it but it really should just be the "nvhpc" or "Nvidia" version.
> 
> If you added batched CUBLAS, I'll take a look, but the dimensions used in CCSD(T) are known to not leverage batching effectively. The current version with async streams splits the batch of GEMMs so adding one batched call is more synchronous. It's unlikely to be better on any NVIDIA GPU, which is the only supported hardware for the code as written.

@jeffhammond , yes these are batched CUBLAS calls. Thanks for the additional information and review!  I can remove the batched calls if you think that makes more sense.

**Comment by jeffhammond** [comment]
I'm on vacation but I'll test the batched stuff when I get back. If it's optional, it shouldn't do any harm to be there.

**Comment by edoapra** [comment]
I have just rebased

**Comment by edoapra** [comment]
@jeffhammond could you please have a look at the commit I have just made to the ccsd USE_OPENACC bit?
https://github.com/nwchemgit/nwchem/pull/980/commits/3052284f9d9fa0f213eb16cdeedd0894535307a0

**Comment by jeffhammond** [comment]
do you have performance numbers for the NVIDIA implementation here?  this is a large change and since i will end up maintaining it, i want to understand what the upside is.

**Comment by edoapra** [comment]
@jeffhammond what environment variables are you use to link when `USE_OPENACC_TRPDRV=1`?

I am getting a bunch of cuda and pgf90/pgi undefined objects.
I can get the link to work by modifying makefile.h with this change
```
diff -u config/makefile.h config/makefile.h.linkcuda 
--- config/makefile.h	2024-07-30 10:23:16.989751519 -0700
+++ config/makefile.h.linkcuda	2024-07-26 11:54:17.992993104 -0700
@@ -3658,7 +3658,7 @@
 
 ifdef NWCHEM_LINK_CUDA
     ifeq ($(_FC),pgf90)
-       CORE_LIBS += -acc -cuda -cudalib=cublas
+       CORE_LIBS += -L/usr/local/cuda/targets/x86_64-linux/lib/ -acc -cuda -cudalib=cublas
     endif
     ifeq ($(_FC),gfortran)
        CORE_LIBS +=  -fopenacc -lcublas
```

**Comment by edoapra** [comment]
@jeffhammond @omarkahmed Should we mark this pull request as draft for the time being?

**Review by jeffhammond — CHANGES_REQUESTED** [review]
Please revert all changes to the OpenACC.F code. They are not good.

**Comment by jeffhammond** [comment]
Intel should just leave my version alone and contribute theirs on its own.

**Comment by omarkahmed** [comment]
@jeffhammond , thanks for the feedback.  Will revert the OpenACC.F modifications.

**Comment by jeffhammond** [comment]
export USE_DEBUG=1
export USE_F90_ALLOCATABLE=y
export USE_OPENACC_TRPDRV=y
export NWCHEM_LINK_CUDA=y

I think the last one is the one that matters, but I’ll check tomorrow.  I already turned my workstation off for the day.

**Comment by edoapra** [comment]
> export USE_DEBUG=1 export USE_F90_ALLOCATABLE=y export USE_OPENACC_TRPDRV=y export NWCHEM_LINK_CUDA=y

My link problem vanished installing a more recent nvhpc release

**Comment by omarkahmed** [comment]
> Please revert all changes to the OpenACC.F code. They are not good.

@jeffhammond , I reorganized the commits to eliminate the changes to the cuda version.  Please let me know if you have any other requests.

**Comment by jeffhammond** [comment]
Thanks.  This good for me.

**Pull request merged**
