### PR TITLE
Fixups for Intel Xe CCSD(T) OpenMP Offload

### PR DESCRIPTION
**Pull request by omarkahmed**
Add a fixup for batched dgemm implementation, and cleaning up ifdefs.

### CODE REVIEW

**Comment by omarkahmed** [comment]
Hi @edoapra , it looks like some of the CI checks are failing due to failing curl commands:
```
downloading dftd3.tgz
chchc curl -f -L https://www.chemie.uni-bonn.de/grimme/de/software/dft-d3/dftd3.tgz/dftd3.tgz -o dftd3.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by jeffhammond** [comment]
See https://github.com/nwchemgit/nwchem/issues/1053

**Comment by edoapra** [comment]
@omarkahmed could you please rebase this branch?

**Review by jeffhammond — APPROVED** [review]
i cannot test this to verify but i have no objections.

**Pull request merged**
