### PR TITLE
add elements 119 and 120

### PR DESCRIPTION
**Pull request by jeffhammond**
since these have 3-character symbols, we add a 3-character symbol array (similar to the 1-character array special cases) and check that after the full element name and before the 2-character symbol check.

we add the first 2 characters of the symbol name to the array of those, which is theoretically unsafe in the event that these are non-unique, but this won't be a problem as long as we check the full name, then the 3 char, then the 2 char.

### CODE REVIEW

**Comment by jeffhammond** [comment]
i will write some tests for this now, because i think we need those

**Comment by jeffhammond** [comment]
I do not know how to write automated tests because the open-shell cases require explicitly multiplicity and I do not know how to generate all of those cases correctly without doing a lot more work.

**Comment by miroi** [comment]
Hi,

for multiplicity, Z=119 is 7s(1), doublet, and Z=120 is 7s(2), singlet.  This is how we interpreted the electronic structure.

**Comment by jeffhammond** [comment]
I am not worried about specific cases.  I was trying to generate a simple test of the atom symbols/names in the input parser for all elements.  It seems I can't do that.

**Review by edoapra — CHANGES_REQUESTED** [review]
This is going to stop for odd number of electrons with the error
```
Odd number of electrons. Please specify a                      restricted open-shell or open-shell calculation
```
I would also get rid of `xc slater` and let the code run both Exchange and Correlation LDA

**Comment by edoapra** [comment]
I am inclined to merge this pull request once the last github action is done.   
The run script can be later improved.   
I have already added one QA test.

**Comment by miroi** [comment]
Ah, it is merged ! Now I am going to try...

**Pull request merged**
