### PR TITLE
detect MPI problems

### PR DESCRIPTION
**Pull request by edoapra**
* Grafted code to check mpirun compatibility from https://github.com/nwchemgit/nwchem/issues/248#issuecomment-690799014

### CODE REVIEW

**Comment by edoapra** [comment]
Converted to draft since we need to tested when srun is used

**Comment by jeffhammond** [comment]
I'll look at this next week. I think I know how to handle various launchers.

**Comment by edoapra** [comment]
My preliminary tests seem to indicate that srun seem to be handled correctly. I still need to see what happens when container images are used (e.g. shifter, singularity/apptainer), but that should not make any difference from a native execution.

I was thinking of not making this check a default execution, and have a set directive to enable it, instead.
This way we can suggest this input modification, for example, to the users that might be in this situation (see multiple postings to the users' forum).
` set check_mpirun t`

**Review by jeffhammond — APPROVED** [review]
i did not test this but i read it and it looks good to me

**Pull request merged**
