### PR TITLE
Fix sign of c5 parameter in HCTH/147

### PR DESCRIPTION
**Pull request by susilehtola**
The same bug also exists in other codes, such as Molpro (https://gitlab.com/libxc/libxc/-/issues/205) and GAMESS-US (https://gitlab.com/libxc/libxc/-/issues/234). LibXC has the correct implementation; the constant is supposed to have a plus sign as in the reference implementation in CADPACK (https://gitlab.com/libxc/libxc/-/issues/205).

### CODE REVIEW

**Review by edoapra — COMMENTED** [review]
@susilehtola thanks for spotting this.
Shouldn't we use all the numbers from column  @TZ2P in table II of https://dx.doi.org/10.1063/1.1589004, instead of just flipping the sign of c5?

**Comment by edoapra** [comment]
@susilehtola thanks for spotting this.
Shouldn't we use all the numbers from column  @TZ2P in table II of https://dx.doi.org/10.1063/1.1589004, instead of just flipping the sign of c5?

**Comment by susilehtola** [comment]
> Shouldn't we use all the numbers from column @TZ2P in table II of https://dx.doi.org/10.1063/1.1589004, instead of just flipping the sign of c5?

That's up to you; it may not be really necessary.

**Comment by susilehtola** [comment]
OK, you added it as a new functional; I guess this should be merged, too?

**Comment by edoapra** [comment]
> OK, you added it as a new functional; I guess this should be merged, too?

No, the idea is to leave hctch147 as it is in NWChem.
If we change the sign, it is very likely that we will have users reporting unreproducible results.
Therefore, the idea is discard this pull request

**Comment by susilehtola** [comment]
> > OK, you added it as a new functional; I guess this should be merged, too?
> 
> No, the idea is to leave hctch147 as it is in NWChem.
> If we change the sign, it is very likely that we will have users reporting unreproducible results.
> Therefore, the idea is discard this pull request

.. but the functional is wrong; this is a bug!!

**Comment by susilehtola** [comment]
@edoapra To clarify, hcth147 and hcth147@tz2p are the same functional. If you look at [J. Chem. Phys. 112, 1670 (2000)](http://doi.org/10.1063/1.480732), the method is the same

> All ab initio and Kohn–Sham calculations were carried out with a TZ2P basis set.

The values of the parameters are also almost exactly the same; the later paper just has more decimals.

The older paper has a misprint for the sign of the c5 parameter; the value used in the code of Boese et al has a plus sign. The results of the paper correspond to the opposite sign of the coefficient.

This can also be verified by pulling in the CADPAC code from the Wayback machine:
https://web.archive.org/web/20110804220952/http://www-theor.ch.cam.ac.uk/software/cadpac/download/sgi.tar

In the tarball, you find the file `results/argon.hcth147.out`, which has a calculation for HCTH-147 on Argon in a 6-31G basis with an additional F function (basis set given in output). The log file gives the energy as `-527.59185980`.

The log file is an authoritative source, since the header is
```
                    ****************************************************
                    *                                                  *
                    *      CAMBRIDGE ANALYTIC DERIVATIVES PACKAGE      *
                    *               ISSUE 6.5 APRIL 2001               *
                    *                                                  *
                    ****************************************************
 Last step        0.00 total used        0.00 remaining    399999.00
 Wed Jun 27 10:56:00 2001
 Run by rda      on                         
       CADPAC6.5   
 Version as at April 2001  
```
which predates the later paper by two years.

Repeating the calculation with a (100,590) quadrature grid, this is what I get:

| | E |
|--|---|
|parameters from 2000 paper, with wrong sign for c5|-527.57268304|
|parameters from 2003 paper, flipped sign of c5|-527.57269188|
|parameters from 2000 paper, fixed sign of c5|-527.59075281|
|parameters from 2003 paper|-527.59080772|
|CADPAC reference value|-527.59185980|

You can see that the more precise values for the parameters have little effect on the energy. A huge difference, however, comes from the wrong sign of the c5 coefficient. This is most definitely a bug in NWChem.

**Comment by edoapra** [comment]
`hcth147` is now deprecated in favor of `hcth147@tz2p`
Users can still use  `hcth147` if they wish to, but the error message clearly points to the the information in this pull request
https://github.com/nwchemgit/nwchem/commit/20f5149f0aa2b2d3e2539a962ef7c114638ebb22

**Comment by susilehtola** [comment]
I would suggest fixing hcth147, and - if you like - adding the broken variant with a different keyword. When the user asks for hcth147 the program should give hcth147, not something else.

**Comment by edoapra** [comment]
Closing this since I don't see any way of converging on this issue

**Pull request closed without merging**
