### PR TITLE
remove obsolete and incorrect versions of TRPDRV

### PR DESCRIPTION
**Pull request by jeffhammond**
1. remove ccsd_trpdrv_nb because it is buggy.  ccsd_trpdrv_omp (OpenMP) has the nonblocking stuff and works.
2. remove all Blue Gene (BG) files since they are obsolete.  the OpenMP version should be fine for BG-like systems.

the former issue was found in the context of ARMCI nonblocking request handles, but i think it might have been observed before.

### CODE REVIEW

**Comment by edoapra** [comment]
@jeffhammond Could you rebase this branch?
https://github.com/jeffhammond/nwchem/tree/disable_ccsd_trpdrv_nb show the following status
[2 commits ahead of](https://github.com/jeffhammond/nwchem/compare/nwchemgit%3Anwchem%3Amaster...disable_ccsd_trpdrv_nb), [64 commits behind](https://github.com/jeffhammond/nwchem/compare/disable_ccsd_trpdrv_nb...nwchemgit%3Anwchem%3Amaster) nwchemgit/nwchem:master.

**Comment by jeffhammond** [comment]
rebase done

**Comment by edoapra** [comment]
> rebase done

Thanks. It might take me some time to go through this pull since the flang-new-20 action might fail and I still not have looked at this compiler issue (clearly orthogonal to the this changes) yet

**Review by edoapra — APPROVED** [review]

**Comment by edoapra** [comment]
Thanks for the code cleanup

**Pull request merged**
