### PR TITLE
OpenACC in TCE CCSD(T) triples

### PR DESCRIPTION
**Pull request by alexwoods14**
Port of the triples method into the TCE CCSD(T) code. On 8 NVIDIA A100s it out performs the CPU code by a factor of 4 and the CUDA implementation by around 10-20%. There are memory limitations for how large the problem used can be

### CODE REVIEW

**Comment by edoapra** [comment]
@alexwoods14 thanks for the contribution.
I have a couple of comments:
* please enable github actions in your own fork before making a pull request so that you can check if your contribution do not break existing functionality. I have just enabled github actions for this pull request and it seems that the CPU based tce method is not working https://github.com/nwchemgit/nwchem/runs/7922693137?check_suite_focus=true
* could you prepare a cleaner pull request without Merge Branch operations?
We had a pull request with several Merge Branch operations that caused major problems to the repository earlier today once the pull request was merged (and the only working fix was to remove the pull request commits)

**Comment by jeffhammond** [comment]
I don't see any merge commits in this PR.  Am I missing something?  I'm asking both for my own education, and because I told Alex I'd help him figure out the upstream process.  Thanks.

**Comment by edoapra** [comment]
> I don't see any merge commits in this PR. Am I missing something? I'm asking both for my own education, and because I told Alex I'd help him figure out the upstream process. Thanks.

Yes, you are right.

**Comment by alexwoods14** [comment]
@edoapra, @jeffhammond. Yes, you're right, there are no merge commits which is a mistake on my part. I submitted this in a hurry and wasn't able to give it the attention required. 

I think I know why the tests are failing so I'll fix that and I'll merge in master when I have the time and resources to do so

**Comment by edoapra** [comment]
> @edoapra, @jeffhammond. Yes, you're right, there are no merge commits which is a mistake on my part. I submitted this in a hurry and wasn't able to give it the attention required.
> 
> I think I know why the tests are failing so I'll fix that and I'll merge in master when I have the time and resources to do so

Please keep in mind that your changes might affect both the CPU based code and the OpenMP offload code.

**Comment by edoapra** [comment]
@alexwoods14 are  `USE_OPENMP`  and `USE_OFFLOAD` incompatible with  `TCE_OPENACC`?

**Comment by alexwoods14** [comment]
@edoapra they are incompatible in the sense that only one can be used in the triples calculation. I need to refactor a few of my preprocessing conditionals to make sure that only 1 can be used at a given time as a few places currently use `#ifdef ... #endif` rather than `#ifdef ... #else ...`

**Comment by edoapra** [comment]
> @edoapra they are incompatible in the sense that only one can be used in the triples calculation. I need to refactor a few of my preprocessing conditionals to make sure that only 1 can be used at a given time as a few places currently use `#ifdef ... #endif` rather than `#ifdef ... #else ...`

Yes, that sounds like a good idea.   
On top of that, I would also try to catch incompatible settings inside GNUmakefile. For example, the following change
```
--- a/src/tce/ccsd_t/GNUmakefile
+++ b/src/tce/ccsd_t/GNUmakefile
@@ -53,6 +53,10 @@ endif


 ifdef TCE_OPENACC
+   ifdef USE_OPENMP
+$(error USE_OPENMP must be unset when TCE_OPENACC is set)
+   endif
+
   OBJ_OPTIMIZE += ccsd_t_kernels_acc.o
   FOPTIONS += -DTCE_OPENACC -acc
 #   ifeq ($(_FC),pgf90)
```
would cause this compilation command to fail
```
 make FC=nvfortran USE_OPENMP=1 TCE_OPENACC=1
GNUmakefile:57: *** USE_OPENMP must be unset when TCE_OPENACC is set.  Stop.
```

**Comment by alexwoods14** [comment]
@edoapra Should be ready to review now. A few comments:

- As you suggested I have added the OpenMP and OpenACC error line  to the makefile although this is in the `config/makefile.h` rather than `tce/ccsd_t/GNUmakefile` as the OpenACC flag wasn't being appended when specified there. However, it can be built with `USE_OPENMP=1` and `TCE_OPENACC=1` without any issues, due to the ordering of the preprocessing conditionals it will prioritise the OpenACC version so this error catching might not even be needed.
- I've also added in a second version for the GPU affinity calculation to be done without CUDA, this means that it can be built and run without CUDA or NVIDIA compilers and hence compiles and runs with an offloading enabled GCC (I assume other compilers which support OpenACC should just work too). I only have NVIDIA hardware to test on but I would assume this works for GPUs by other vendors too.
  - I'd expect the original version that uses CUDA could be replaced with the new version using `acc_get_num_devices` but I haven't gone so far as to replace it myself in case it has benefits which I am unaware of

**Comment by edoapra** [comment]
@alexwoods14 Thanks for updating the description.
Could you also provide more details of the benchmarks you alluded to? For example: input file, number of processes/GPU, etc ...

**Comment by alexwoods14** [comment]
Sure, The input file is a simple w5 TCE input generated with Jeff's input generator: https://github.com/NWChem/input-generator using `./make_nwchem_input.py  w5  ccsd-t cc-pvtz energy`
The only thing changed in the input is to remove `set tce:xmem ...` This could be mitigated by added a preprocessing conditional to call the non-sliced code but I haven't done that.

Using 2x AMD 7713 processors (128 processes) the triples portion of the calculation takes 955.7 seconds. Using 8 40GB NVIDIA A100s, the triples portion takes 277.0 seconds with CUDA and 212.0 seconds with the new OpenACC version. 2 A100 GPUs with OpenACC gives a time of 840.8 seconds so still faster than the CPU only.

The main limitation is the memory, a w7 input is too large to fit in the GPU memory with 128 cores. The two ideas I have for this are to try porting over into the sliced code. I'll try that in the next few days/weeks (and another pull request) which should be fairly quick although I don't know if it will have any benefit. Alternatively it might be beneficial to not offload from all processes. i.e. only using 1 or 2 processes per GPU to offload with. I don't know a huge amount about GlobalArrays although assuming it is like other PGAS approaches this shouldn't be too complicated. The CUDA version doesn't have this limitation so I'll look into how that handles it but I expect it'll be trickier with OpenACC due to having less fine grained control and this change could take me longer to figure out

**Comment by jeffhammond** [comment]
We can idle some processes in the triples offload. That should not be hard to implement. I don't have time right now but I can work on it in a few weeks. The easy workaround right now is to use fewer processes per node from the outset.

**Comment by edoapra** [comment]
@alexwoods14 Could you move the `CORE_LIBS` options in `makefile.h` to `LDOPTIONS`, instead?
Similar story for `util/GNUmakefile`, please move `-DUSE_OPENACC_AFFINITY` to  
 `LIB_DEFINES`  
`src/tce/ccsd_t/GNUmakefile`  does  not seem to have any real change. I would not push this.e

Could you  generate a new pull request, with the changes above and on top of the current master (so that there are no merges)?

**Comment by alexwoods14** [comment]
Yes I'll do that. I spotted that there were no changes to `src/tce/ccsd_t/GNUmakefile` and thought I had fixed that already.

Do you mean to merge the latest 2 commits into my fork for this pull request or to create a new pull request with my commits rebased onto the top of current master? When I submitted the review request my version was up to date with master + my commits

**Comment by alexwoods14** [comment]
Ok. Will do. That merge there was unintentional. I meant to click the discard commits button to set my forks master to nwchemgit master. I'll close this PR and will start a new one when I'm done

**Comment by alexwoods14** [comment]
@edoapra Would you prefer if I squash the commits into one or leave them as they are?

**Comment by edoapra** [comment]
> @edoapra Would you prefer if I squash the commits into one or leave them as they are?

It's up to you.

**Pull request closed without merging**
