### PR TITLE
Add support for i-PI communication over UNIX sockets

### PR DESCRIPTION
**Pull request by ehermes**
Add support for i-PI communication over UNIX sockets. The syntax is:

```
driver
    socket unix my_socket_name
end
```
NWChem will create a UNIX socket file located at `/tmp/ipi_my_socket_name`, per the i-PI protocol standard. To be clear, `my_socket_name` can be any valid UNIX file name, except that it may not include spaces.

IP sockets can still be used if the argument `unix` is replaced by any other keyword.

### CODE REVIEW

**Comment by ehermes** [comment]
Note that this doesn't (currently) affect the i-PI socket implementation in NWPW, which still only supports IP sockets.

**Comment by ehermes** [comment]
I've now also implemented UNIX sockets for the NWPW i-PI implementation. The syntax is:

```
nwpw
    socket <protocol> <target>
end
```

Where `<protocol>` must be either `unix` (for UNIX sockets) or `ipi_client` (for IP sockets). `<target>` is a unique file name suffix (with prefix `/tmp/ipi_`) for UNIX sockets or a hostname:port pair for IP sockets.

Unlike the implementation in `driver`, you must set `protocol` to `ipi_client` if you wish to use IP sockets (whereas in `driver`, any setting other than `unix` will use IP sockets). Perhaps this should be changed. Input is welcome.

**Comment by ehermes** [comment]
I see that there's a new branch for the upcoming 7.0 release of NWChem. Please consider incorporating this PR into the 7.0 release, as it extends the existing i-PI socket communication functionality to fully comply with the i-PI standard, which will really help other projects that rely on i-PI sockets. I'd be happy to make any changes that the project maintainers feel are necessary.

**Comment by ebylaska** [comment]
Works for me.

**Pull request merged**
