### PR TITLE
Fix url in build_dftd3a.sh

### LINKED ISSUE #1053: Problem with downloading DFT-D3 library
I am having issues with the `build_dftd3a.sh` script used in the build process of NWChem to download the DFT-D3 library, in version 7.2.3 of NWChem

I personally have been getting the following output from this script since around last Friday:
```
$ ./build_dftd3a.sh 
downloading dftd3.tgz
chchc curl -f -L https://www.chemie.uni-bonn.de/grimme/de/software/dft-d3/dftd3.tgz/dftd3.tgz -o dftd3.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
attempt no. 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
attempt no. 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
curl: (22) The requested URL returned error: 404
attempt no. 4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
attempt no. 5
download failed
if internet connectivity is missing
set NO_NWPWXC_VDW3A=1

```

I think looking at the source file, the first link is incorrect
```
URL1="https://www.chemie.uni-bonn.de/grimme/de/software/dft-d3/dftd3.tgz"
```
because as demonstrated in the log, `dftd3.tgz` is appended to the string, so it gets added twice. The alternative link,
```
URL2="https://web.archive.org/web/20210527062154if_/https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/"
````
seems to be a dead link to me now (https://web.archive.org/web/20210527062154if_/https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/dftd3.tgz).

I've been working around the problem by changing the first URL to strip the filename, but I thought I should flag up the issue, in case that other users are affected. Thanks for looking at this.

### PR DESCRIPTION
**Pull request by haampie**
Closes #1053

I guess this was never tested.

### CODE REVIEW

**Review by jeffhammond — APPROVED** [review]
verified as correct

**Comment by jeffhammond** [comment]
LGTM but I will let @edoapra hit the merge button.

**Comment by edoapra** [comment]
> Closes #1053
> 
> I guess this was never tested.
I agree that the first URL was incorrect, but the the second one out of webarchive.org used to work until a few weeks ago.
Therefore, please keep your rushed conclusion to yourself.
We do extensive tests of NWChem as anyone can see from the github action logs.
I  have not been able to spot the same level of robust testing in spack yet.

**Comment by chenrui333** [comment]
@edoapra currently the build failed, any chance to cut a new release for this PR fix? thanks!

**Comment by edoapra** [comment]
> @edoapra currently the build failed, any chance to cut a new release for this PR fix? thanks!

This is for the NWChem homebrew recipe, right?

**Comment by edoapra** [comment]
> @edoapra currently the build failed, any chance to cut a new release for this PR fix? thanks!
@chenrui333 
It sounds like you have already applied this fix ... isn't it?
https://github.com/Homebrew/homebrew-core/commit/646bfc53f1095ba234d294ee747713ae957e3b40
https://github.com/Homebrew/homebrew-core/commit/646bfc53f1095ba234d294ee747713ae957e3b40#diff-6f40a68c218c50c802e5a7cb64a559f6ac3f8bb8e7541f5929373a18ac6b5af1R39

**Pull request merged**
