### PR TITLE
clean up POPCOUNT stuff

### LINKED ISSUE #216: cleanup SELCI popcount
The SELCI module contains a bunch of 20 year-old code to compute POPCOUNT, all of which look awful except for the Cray T3E case that uses the Fortran 2008 intrinsic (before it was standard, of course).

We should considering removing all the Fortran stuff and just wrap `__builtin_popcount` that exists in C compilers (and maps to hardware when available), and fall back on the simple C implementation from Wikipedia:
```c
int popcount64d(uint64_t x)
{
    int count;
    for (count=0; x; count++)
        x &= x - 1;
    return count;
}
```

Or we can use what we already have in https://github.com/nwchemgit/nwchem/blob/master/src/util/util_intrsc2008.F.

@hjjvandam Why don't we have an option to use Fortran 2008 POPCOUNT when it is available?

### PR DESCRIPTION
**Pull request by jeffhammond**
Resolves #216 

- remove inibit, which apparently optimized for Sun 20 years ago
- remove all hand-rolled POPCOUNT
- use util_popcnt by default
- use popcnt intrinsic if env var set (not set anywhere right now)

Signed-off-by: Jeff Hammond <jeff.r.hammond@intel.com>

### CODE REVIEW

**Comment by jeffhammond** [comment]
That error only occurs with `util_popcnt`.  I do not see it with `popcnt`.

@hjjvandam Did you explicitly verify `util_popcnt` is correct?

**Comment by edoapra** [comment]
> 
> 
> That error only occurs with `util_popcnt`. I do not see it with `popcnt`.
> 
Yes, if I compile with the define `NWCHEM_USE_FORTRAN2008`, everything works.
What about just keeping the code using `popcnt` and getting rid of `util_popcnt`?
One less bit of code to maintain.

**Comment by jeffhammond** [comment]
@edoapra That works for me.  I share you attitude but wasn't sure that unconditional Fortran 2008 was allowed.

**Comment by jeffhammond** [comment]
It would appear that the `h2o_selci` QA test is nondeterministic.  It crashes, produces the wrong answer and gives the correct answer with approximately equal frequency.  I wonder if we should just delete SELCI altogether...

**Comment by jeffhammond** [comment]
Err, it has something to do with automatic reuse of scratch files.  Lovely.

**Comment by edoapra** [comment]
Yes, I would be tempted to do delete it altogether.

This is probably the reason why we never added h2o_selci to doqmtests.mpi

On 6/16/20 2:08 PM, Jeff Hammond wrote:

It would appear that the h2o_selci QA test is nondeterministic. It crashes, produces the wrong answer and gives the correct answer with approximately equal frequency. I wonder if we should just delete SELCI altogether...

**Comment by jeffhammond** [comment]
It is deterministic when I clean the temp files beforehand.

**Pull request merged**
