### PR TITLE
X2c pr

### PR DESCRIPTION
**Pull request by jautschbach**
Scalar X2C Hamiltonian module added to DFT code. QA test case x2c-h2se.

### CODE REVIEW

**Comment by edoapra** [comment]
@jautschbach could you extract  the changes to `dft_scf.F` in a separate/new routine?

**Comment by jautschbach** [comment]
No. I talked with Niri about this earlier today. He will probably look into
this eventually, but for now the functionality needs to interface with the
DFT routine in the same way as Niri's ZORA code, which is how it's done.

**Comment by edoapra** [comment]
> No. I talked with Niri about this earlier today. He will probably look into this eventually, but for now the functionality needs to interface with the DFT routine in the same way as Niri's ZORA code, which is how it's done.
>

Got you. I will wait accepting this pull request until this problem is addressed.

**Comment by jautschbach** [comment]
I wrote that Niri will probably look into this eventually. That does not
mean the pull request should be put on hold. For the time being this is
meant to go into the DFT code, and perhaps it'll stay there indefinitely.

**Comment by jautschbach** [comment]
P.S. To avoid further misunderstandings about this: The pull request
should be acted upon. There is no reason to wait.

I was only providing some background information.

J/

**Comment by edoapra** [comment]
Morphed into https://github.com/nwchemgit/nwchem/pull/591

**Pull request closed without merging**
