### PR TITLE
Sonadc stubbing

### PR DESCRIPTION
**Pull request by edoapra**
Moved aoints and sifs directories under new sonadc top level directory.
This allows stubbing of the aoints and sifs functionality.
New github actions jobs are testing the compilation of the non default sonadc module.

### CODE REVIEW

**Comment by edoapra** [comment]
@lachlanbelcher   your feedback is very welcome

**Comment by lachlanbelcher** [comment]
I don't see any problem doing it this way, but it might be more helpful to label it "columbus" instead of just "sonadc"

**Comment by edoapra** [comment]
> I don't see any problem doing it this way, but it might be more helpful to label it "columbus" instead of just "sonadc"

@lachlanbelcher 
What about nwc_columbus instead of just columbus?
This would make clear that is an interface between nwchem and columbus and avoid conflicts if there is ever going to be a library named libcolumbus.*

**Comment by lachlanbelcher** [comment]
Yes that sounds good

**Comment by lachlanbelcher** [comment]
How does one get it NWChem to compile this part of the code now?

**Comment by lachlanbelcher** [comment]
NWCHEM_MODULES="all" doesn't seem to catch it.

**Comment by edoapra** [comment]
> NWCHEM_MODULES="all" doesn't seem to catch it.

Yes, that's the whole point of stubbing. You need to explicitly add `nwc_columbus` to the list of modules. 
Once we see that the module is more stable, we will think about  moving it back to all.

**Pull request merged**
