### PR TITLE
ccsd trpdrv openacc async redo

### PR DESCRIPTION
**Pull request by jeffhammond**
new PR per https://github.com/nwchemgit/nwchem/pull/589#issuecomment-1098600769

### CODE REVIEW

**Comment by jeffhammond** [comment]
@edoapra The file is named for OpenACC but I also use CUDA Fortran syntax, which is only supported by the NVHPC compiler.  I also use the Fortran module API support available from NVHPC Fortran, which GCC Fortran could support if someone wrote the modules.  Thus, this source file only works with our compiler, hence I'm only registering our flags.

If it helps to rename the file to "_nvidia.F" or "_cuda.F" to make it more clear, I'm fine with that.

Also, as far as 132 columns goes, this is portable, because it's required in the Fortran standard now in free source form (which isn't actually free, as it turns out).

**Comment by jeffhammond** [comment]
I'm willing to try to write a pure OpenACC version of this, but the problem is the CUBLAS Fortran API requires our compiler, so I'd have to write my own wrapper to the C API to invoke it from OpenACC Fortran.

**Comment by jeffhammond** [comment]
I have thought about it a lot, and the only way to make this code portable is to rewrite it in C99 (as I did in that other PR) and then have a dispatch to one of the three vendor GPU BLAS libraries.  I don't have any plan to do that, although I put the code on GitHub so if Intel or AMD wants to do it, they are free to do so.

**Comment by nwchemgit** [comment]
The pull request seemed to go through successfully this time

**Pull request merged**
