### PR TITLE
Support for Intel nextgen compilers

### PR DESCRIPTION
**Pull request by mjklemm**

### CODE REVIEW

**Comment by jeffhammond** [comment]
@edoapra I'm going to do a full build and QA test on a non-Intel machine to verify that this is working in a clean environment, then I'll merge.

**Comment by jeffhammond** [comment]
@mjklemm FYI

I'll try to work around this but for now I am just going to skip FEFF.

```
Compiling feff6Lib.f...
 Intel(R) Fortran 21.0-1663a
 Intel(R) Fortran 21.0-1663a
 Intel(R) Fortran 21.0-1663a
feff6Lib.f(335): warning #6371: A jump into a block from outside the block may have occurred.   [350]
      if (iter.eq.2) go to 350
---------------------------^
feff6Lib.f(3740): catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for feff6Lib.f (code 1)
```

**Comment by jeffhammond** [comment]
Builds fine with these settings:
```sh
export NWCHEM_TOP=$HOME/NWCHEM/github
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES=qm

export FC=ifx
export CC=icx
export CXX=icpx

export USE_MPI=T

export MPIFC=mpiifort
export MPIF77=mpiifort
export MPICC=mpiicc
export MPICXX=mpiicpc

export USE_INTERNALBLAS=y

# GA configure incorrectly parses IFX explicit linking because of "-mllvm -loopopt=0" so I do this manually in $NWCHEM_TOP/src/tools/build
# ../ga-5.7.2/configure --prefix=/home/jrhammon/NWCHEM/github/src/tools/install --with-tcgmsg --with-mpi --enable-peigs --enable-underscoring --disable-mpi-tests --without-scalapack --without-lapack --without-blas --with-mpi-ts CC=mpiicc CXX=mpiicpc F77=mpiifort CFLAGS=-fPIC ARMCI_DEFAULT_SHMMAX_UBOUND=131072
```

**Comment by edoapra** [comment]
@jeffhammond do you want to review these changes or can I go ahead and click the "Merge pull request" button?

**Pull request merged**
