### PR TITLE
Rework ifx compiler configuration

### PR DESCRIPTION
**Pull request by mjklemm**
This commit is to rework the configuration of the new Intel(R)
Fortran compiler in the build system.  The compiler is no longer
a variant of the traditional Intel(R) Fortra compiler.

Compiler debugging can be enabled by setting IFX_DEBUG=1 in the build
environment.

### CODE REVIEW

**Comment by jeffhammond** [comment]
@edoapra There is a lot of overlap but the OpenMP behavior, particularly w.r.t. GPU, will be different, and @mjklemm wants to separate out `FC=ifx` so that we can avoid more tedious detection of OpenMP support.  If we don't separate IFX, we'll probably need a one-off flag like `USE_IFX=y` and that ends up being more error-prone.

**Comment by edoapra** [comment]
@jeffhammond Thanks for the explanation.
Would it be possible to simply separate the OpenMP part, and keep the rest of the options together with ifort?
What I am suggesting is to add the conditional  FC=ifx inside the _FC=ifort part, just for the OpenMP components

**Comment by jeffhammond** [comment]
I'll let @mjklemm comment on that since this is his change. We haven't discussed this in detail yet.  I understand his high-level motivation but there may be some nuances I'm missing.

**Comment by mjklemm** [comment]
The idea was to be able to control on a finer grained level what compiler options are passed to fix. 

Right now it seems like most options are the same, but the differences will start with OpenMP options (-qopenmp will be -fiopenmp once I finished testing).  There might additional flags to control arithmetics, as LLVM might Desk with FP differently than the ifort compiler. 

We could factor out the defines for OpenMP and offload into their own section and also remove them from the ifort configuration as well as the xlf configuration.

**Comment by jeffhammond** [comment]
We should probably refactor makefile.h if we want to have orthogonality where feasible.

**Comment by mjklemm** [comment]
Yes, that's what I was saying.

The OpenMP feature configuration (-DUSE_OPENMP, etc.) could go into a central place and be defined once per compiler.  Only the compiler-specific part (-qsmp vs. -fopenmp vs. -fiopenmp) would then go into the compiler-specific part.

I can refactor this pull request, so that we can look at it.

**Comment by mjklemm** [comment]
@edoapra @jeffhammond Please have a look at the PR now.  OpenMP configuration options are now in their own section and orthogonal to the compiler configuration.  I have not refactored ifort and xlf yet, as I first wanted to get your opinion if this is the right direction before touching all the other compilers.

**Comment by edoapra** [comment]
The new commits don't seem to improve the original commit to me

**Comment by mjklemm** [comment]
@edoapra The ifx compiler is technically a new compiler that will have many nuances about how it works.  The first and foremost instance is that the OpenMP compiler flag is no longer -fopenmp or -qopenmp, but -fiopenmp.  Over time, there will be more compiler flags that I will to the fix settings.  Finally, we might need to specialize for ifx version similar to what has been done for ifort already.

With the previous design where ifx was a special case of ifort, it was very hard to inject the proper compiler flags.  OpenMP support alone would have been another "if ifx then this if ifort then that".  This will over time lead to more convoluated and hard to understand (and hard to get working correctly) makefile code than my proposed change.  I see that it's a bit more code, but since the code is easier to read I see some merits to moving the ifx stuff out of the ifort configuration.

**Comment by mjklemm** [comment]
BTW, I have quickly checked the configuration for ifort and the changes I will have to make for ifx to use GPUs will be about the same number of lines as my indented modification to have a separate ifx configuration.

**Pull request merged**
