### PR TITLE
Columbus sonadc

### PR DESCRIPTION
**Pull request by lachlanbelcher**
Adding functionality to support COLUMBUS integration.  Specifically adds tasks: 
aoints--creates an integral file in the sifs format)
nwgrd--calculates energy gradients by tracing a density matrix file (provided by COLUMBUS) with integrals calculated on the fly
nwnad--calculates non-adiabatic adiabatic couplings in a similar fashion.

Made changes to the sifs build shell and GNU makefile to get it to run.  properly.

Since two of these tasks require an input file created by COLUMBUS, I'm not sure how to set up a proper test without providing a binary file.  Any suggestions welcome.

### CODE REVIEW

**Comment by edoapra** [comment]
A couple of comments:
* Could you enable github actions in your own fork before doing a pull request? I don't see any trace of runs under https://github.com/lachlanbelcher/nwchem/actions.
* Please prepare a clean pull request without merge operations  (e.g. https://github.com/nwchemgit/nwchem/pull/735/commits/81c5bb385b5b8b21231e1ca94fc287c11a678695). In other words, please start from the current master and apply only your changes on top of it

**Comment by lachlanbelcher** [comment]
Hi Edoardo,
On the first point, I enabled the workflows.

On the second point, I believe that's what I did.  Today my fork was 6
commits ahead and 195 commits behind master, so I removed my 6 commits and
synched my fork to the master.  Then I pulled and updated the files that
were different.

**Comment by lachlanbelcher** [comment]
Ok, I think I see what you mean.  If you send back the pull request, I will try to fix it without the merge.  Thanks!

**Comment by lachlanbelcher** [comment]
Hi Edoardo,

Is there any insight as to why my fork keeps failing on the dft_he2+
tests?  It passes on my system, so I can't figure out why it's failing
during the QA test actions.

Thanks,

Lachlan

**Comment by edoapra** [comment]
The error is in the gradient code.
I saw that you add a new argument to some of the integrals derivative routines. This  could be the issue.
You have added the routine in some files, but you are likely to have missed some. I am not suggesting to chase all the calls you missed.
Instead, In order to improve compatibility, instead of adding a new argument I would suggest the following.
* rename the routines you have with the extra argument (for example `intd_1eov()` to `intd_1eov_gen()`)
* create a small wrapper routine with the old name and with the same number or arguments as before.
It would need to set appropriately  the new extra argument  (`hlfdrv=.false.` in the example below, if I got the logic of the new routines right ...)
This is an approximate example
```
      subroutine intd_1eov(i_basis,ish,j_basis,jsh,lscr,scr,
     &       lOva,Ova,idatom)
      implicit none
...
      call intd_1eovP_gen(i_basis,ish,j_basis,jsh,lscr,scr,
     &       nint,Ova,idatom, .false.)
```

**Comment by edoapra** [comment]
In this case, it does not make much sense having a QA test in NWChem for a task that require binary files.

**Pull request closed without merging**
