### PR TITLE
F18 compiler support

### PR DESCRIPTION
**Pull request by jeffhammond**
Work in progress. Do not merge.

### CODE REVIEW

**Comment by jeffhammond** [comment]
@naromero77 Was this patch right and should we merge?

**Comment by naromero77** [comment]
The patch is correct, but I am going to leave it up to you guys at whether it should get merged in. Here are some things to consider:
1. F18 is not a real compiler at the moment. Its just a front-end. It will be a real compiler hopefully in a couple of months.
2. Strong possibility that f18 will get renamed to flang. Then there will be two flangs, "classic" / "legacy" flang and the new flang. We really need to come up with better names to distinguish them, by I think they will both just end up being called flang.
3. Only a handle full of people in DOE who are going to be attempting to compiled NWChem with f18. In fact, I don't expect anyone besides me to attempt it.
4. Its possible to control the f18 "backend" so it uses gfortran, instead of pgf90 by setting an appropriate environment variable that is specific to f18,

I don't think it will do harm either way, if you merge it in or not.

**Comment by jeffhammond** [comment]
I'm inclined to merge this even if it only solves the problems of a few DOE folks, because that is who pays the bills for NWChem, after all :smile: 

If you want support for F18@GCC, I can add a one-off environment variable for that, unless there is a way to query f18 directly.  Is that possible?  Is there a `f18 --backend` that returns PGI or GCC (or anything like that)?

**Comment by naromero77** [comment]
Sure merged it in. You can control the `f18` backend using `F18_FC` environment variable. The default is `pgf90`. I know some people set it to`F18_FC` for testing purposes. There is no way to query f18 directly as far as I know.

**Comment by naromero77** [comment]
We just changed the default behavior of f18 to `gfortran` instead of `pgf90`. We also in the middle of trying to figure out what is the right way to distinguish between classic flang and f18 (new flang). (e.g. with a flag or querying major version numbers).

**Pull request closed without merging**
