### PR TITLE
Srp hpc

### PR DESCRIPTION
**Pull request by nkhumalo**

### CODE REVIEW

**Comment by edoapra** [comment]
@nkhumalo there is no description of what this pull request is about and commits are not incremental, neither the commit log seems very clear to me.
On top of it, why isn't @hjjvandam (the author of the changes) the author of the pull request?

**Comment by hjjvandam** [comment]
Hi Edo,
This is something that Nothando and myself are working on. In order to share the code I was trying to get these changes into my personal fork of NWChem where I keep experiments with various ideas. It seems that these changes ended up getting pushed to the wrong upstream. Let me figure this out.
Best wishes,
Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, ***@***.******@***.***>
Brookhaven National Laboratory, orcid.org/0000-0002-0876-3294<http://www.orcid.org/0000-0002-0876-3294>


From: Edoardo Aprà ***@***.***>
Reply-To: nwchemgit/nwchem ***@***.***>
Date: Thursday, September 1, 2022 at 20:14
To: nwchemgit/nwchem ***@***.***>
Cc: "Van Dam, Hubertus" ***@***.***>, Mention ***@***.***>
Subject: Re: [nwchemgit/nwchem] Srp hpc (PR #644)


@nkhumalo<https://github.com/nkhumalo> there is no description of what this pull request is about and commits are not incremental, neither the commit log seems very clear to me.
On top of it, why isn't @hjjvandam<https://github.com/hjjvandam> (the author of the changes) the author of the pull request?

**Comment by edoapra** [comment]
> Hi Edo, This is something that Nothando and myself are working on. In order to share the code I was trying to get these changes into my personal fork of NWChem where I keep experiments with various ideas. It seems that these changes ended up getting pushed to the wrong upstream. Let me figure this out. Best wishes, Huub

Does this mean that it is OK to close  this pull request for the time being?

**Comment by edoapra** [comment]
@hjjvandam Since this pull request seem still in flux (and with any real description nor summary of the changes), I am going to close it.

**Comment by hjjvandam** [comment]
Hi Edo,
I think that is fine.
Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, ***@***.******@***.***>
Brookhaven National Laboratory, orcid.org/0000-0002-0876-3294<http://www.orcid.org/0000-0002-0876-3294>


From: Edoardo Aprà ***@***.***>
Reply-To: nwchemgit/nwchem ***@***.***>
Date: Tuesday, September 6, 2022 at 12:41
To: nwchemgit/nwchem ***@***.***>
Cc: "Van Dam, Hubertus" ***@***.***>, Mention ***@***.***>
Subject: Re: [nwchemgit/nwchem] Srp hpc (PR #644)


@hjjvandam<https://github.com/hjjvandam> Since this pull request seem still in flux (and with any real description nor summary of the changes), I am going to close it.

**Pull request closed without merging**
