### PR TITLE
Columbus sonadc

### PR DESCRIPTION
**Pull request by lachlanbelcher**
Hello, 
This is a new feature from L Belcher and G Kedziora to make NWChem available for use in COLUMBUS.  This update allows NWChem to write integral files in the sifs format that COLUMBUS uses.  It also allows COLUMBUS to feed NWChem density files to calculate spin-orbit gradients and non-adiabatic derivative coupling terms.  It adds three new tasks:
task_aoints: writes the aoints file in sifs format
task_grdtrc: using provided density files, compute the traces required to calculate analytic MRCI gradients per H. Lischka, M. Dallos, and R. Shepard, Mol. Phys. 100, 1647 (2002).
task_nadtrc: using provided density files, compute the traces required to calculate analytic MRCI gradients per H. Lischka, M. Dallos, P. Szalay, D. Yarkony and R. Shepard, J. Chem. Phys. 120, 7322 (2004).

I have started three new tests; however, I'm still not sure how to bring auxiliary files (apart from the .nw and .out) over to the scratch file for running as part of doqmtests.mpi.

### CODE REVIEW

**Comment by edoapra** [comment]
@lachlanbelcher could you prepare a pull request based on the current master branch without any merge commit (e.g. https://github.com/nwchemgit/nwchem/pull/700/commits/0f0d29e41f4c8e66dbca337c166d8527f0ab0483)?

We had some issued caused by pull requests of this kind that resulted in corruption of the NWChem repository.

**Review by edoapra — CHANGES_REQUESTED** [review]
I don't see any reason to push to the repository Slurm or PBS files

**Review by edoapra — CHANGES_REQUESTED** [review]
Please don't commit binary or temporary files used in a calculation.
For example: 
*.db
bummer
aodens
iwfmtin

**Review by edoapra — CHANGES_REQUESTED** [review]
Please do not commit log files such as QA/doqmtests.log and binary integrals files

**Review by edoapra — CHANGES_REQUESTED** [review]
Please don't move files in the nwdft sub-directories.
Any reason for moving dft_scaleig.fh from include to scf_dft?

**Review by edoapra — CHANGES_REQUESTED** [review]
I don't see the point of this change to QA/runtests.mpi.unix

echo " scrath = $SCRATCHDIR"

**Review by edoapra — CHANGES_REQUESTED** [review]
[src/NWints/aoints/GNUmakefile](https://github.com/nwchemgit/nwchem/pull/700/files#diff-bdf6dba2d9373c4f043dcaf6c4c0b3ad01def9a05902416ba2aba487a7eae645)   
Please remove compiler specific options (FOPTIONS)  
Are all these LIB_INCLUDES needed? Please use only the necessary ones

**Comment by lachlanbelcher** [comment]
> @lachlanbelcher could you prepare a pull request based on the current master branch without any merge commit (e.g. [0f0d29e](https://github.com/nwchemgit/nwchem/commit/0f0d29e41f4c8e66dbca337c166d8527f0ab0483))?
> 
> We had some issued caused by pull requests of this kind that resulted in corruption of the NWChem repository.
> 
> Please do have your fork pass the github action tests before issuing the pull request https://github.com/lachlanbelcher/nwchem/actions/runs/3576527008

Thanks for the input.  Unfortunately, I do not see an option in github to revert the merge request.  Do you know how I find that button?

**Comment by edoapra** [comment]
> > @lachlanbelcher could you prepare a pull request based on the current master branch without any merge commit (e.g. [0f0d29e](https://github.com/nwchemgit/nwchem/commit/0f0d29e41f4c8e66dbca337c166d8527f0ab0483))?
> > We had some issued caused by pull requests of this kind that resulted in corruption of the NWChem repository.
> > Please do have your fork pass the github action tests before issuing the pull request https://github.com/lachlanbelcher/nwchem/actions/runs/3576527008
> 
> Thanks for the input. Unfortunately, I do not see an option in github to revert the merge request. Do you know how I find that button?

There is not an automated way that I know of.  
I would suggest you the following:
1. Get a new branch on your fork in sync with the current master
2. Apply your changes on top of this branch

Please do not commit files that are not needed as it was in this pull request.

**Review by edoapra — COMMENTED** [review]
src/NWints/sifs/sif2w8.F seems the same file as the following file https://gitlab.com/columbus-program-system/columbus/-/blob/master/Columbus/source/gcfci/colib/sifs/sif2w8.F other than the omission of the LGPL v3 file ... I believe that
1. this license header cannot be omitted and
2. Columbus LGPL v3 license is not compatible with NWChem ECL 2.0 license  
Therefore these file cannot be added to the NWChem source

**Comment by lachlanbelcher** [comment]
Hi Edoardo,

Could you elaborate on why the licenses would be incompatible?

Thanks,

Lachlan

**Comment by edoapra** [comment]
ECL 2.0 code can be introduced into LGPL 3.0 code, but not the other way around. 
ECL 2.0 is a very close to Apache 2.0 https://www.gnu.org/licenses/license-list.en.html#ECL2.0 
You can see a chart of the compatibility among open-source licenses at https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses

**Comment by edoapra** [comment]
You can use the same approach mentioned at https://github.com/nwchemgit/nwchem/pull/700#pullrequestreview-1198489581 to avoid using the Columbus source code.
Here is a pull request with the needed modifications, download script included
https://github.com/nwchemgit/nwchem/pull/701

**Pull request closed without merging**
