### PR TITLE
occupied and virtual IBOs

### PR DESCRIPTION
**Pull request by jautschbach**
updated IBO code to allow for occ and virt IBO construction. localization input and driver were updated, along with the QA job localize-ibo-aa. nwparse.pl now tests for completion of IBO run.

### CODE REVIEW

**Comment by jautschbach** [comment]
There are many functional changes, but along the way I also removed a bunch
of trailing white spaces in the file. Let's keep the commit as-is. I don't
have time to restore the white space and everything compiles and runs fine,
so what's your issue?

**Comment by edoapra** [comment]
Thanks for the quick response. My comment is related to maintenance of the code. If a later time a bug show up caused by one the files changed here, the large number of cosmetic changes will make the bug chasing/fixing much harder. That's my perspective as software maintainer.

**Comment by jautschbach** [comment]
I pushed another commit reverting non-essential changes in
ddscf/localize.F. Checks are running

**Comment by edoapra** [comment]
morphed into https://github.com/nwchemgit/nwchem/pull/742 after removing whitespaces

**Comment by edoapra** [comment]
@jautschbach I missed your https://github.com/nwchemgit/nwchem/pull/741#issuecomment-1448929524 comment

**Pull request closed without merging**
