### PR TITLE
fix for nvfortran 22.5

### PR DESCRIPTION
**Pull request by edoapra**
Fix for issue https://github.com/nwchemgit/nwchem/issues/619

### CODE REVIEW

**Comment by edoapra** [comment]
@jeffhammond thanks for the update. 
I should be able to localize the fix for 22.5.
Any estimate for the date of the next release?

**Comment by jeffhammond** [comment]
22.5 just dropped so I guess 22.7 is coming in 6-10 weeks. That's our release cadence.

**Comment by edoapra** [comment]
@jeffhammond is this 22.5 bug likely to be present in the ARM architecture, too?

**Comment by jeffhammond** [comment]
Not sure. It may be a special case optimization for x86. I'll have to ask.

**Pull request merged**
