### PR TITLE
CCSD trpdrv with C99 OpenMP

### PR DESCRIPTION
**Pull request by jeffhammond**
This adds new versions of TRPDRV, the most important of which is a C99 version, which can be used as the starting point for various programming models that are more compatible with C than with Fortran.  It also contains a test driver that serves as a proxy for the compute portion of (T), which is really useful for running in computer hardware simulator environments.

### CODE REVIEW

**Review by edoapra — CHANGES_REQUESTED** [review]
Would line `1288` in `src/config/makefile.h` force the use of MKL libraries? I think we want to have the flexibility to be able to use BLAS libraries other than MKL when compiling with ifort
Do you think the the github actions failure of this pull request are related to this?

**Comment by jeffhammond** [comment]
I will fix these issues.  I wasn't sure if the new code was even going to be built by default.

I have tested with MKL and Apple Accelerate but any CBLAS implementation should work.  I will add the right preprocessor guards to make sure that the C99 version is only compiled when CBLAS is available.

**Comment by jeffhammond** [comment]
Should be fixed now.  It's not perfect and I should build all the infrastructure for CBLAS but the current setup is fine since no one will be running this code unless they've read the source and use set directives.

This is the baseline for a future CUDA version, but I need to get the C99 stuff in first.  The CUDA version will do more in the build system since there will be exactly one way to build that version correctly due to the dependence on CUBLAS.

**Comment by edoapra** [comment]
the `mkl.h` issue when using `ifort` is still there
https://github.com/nwchemgit/nwchem/pull/339/checks?check_run_id=2083980570

**Comment by jeffhammond** [comment]
Weird.  That means `icc` isn't supporting `-mkl`.  Can you add `VERBOSE=1` or `V=1` (whatever turns on the verbose printing of compiler commands) in the CI system so I can see what is actually being used?

If this build uses gcc+ifort, that's the problem and I'll fix it.

**Comment by edoapra** [comment]
> If this build uses gcc+ifort, that's the problem and I'll fix it.

Yes, I think this is the case. See 'CC=cc' below. I think we need to cover this case, too.
https://github.com/nwchemgit/nwchem/pull/339/checks?check_run_id=2083980535
```
*** Configuring Parallel Tools ****

../ga-5.8/configure --prefix=/home/runner/work/nwchem/nwchem/src/tools/install SCOREP_WRAPPER=OFF --with-tcgmsg --with-mpi=-I'/opt/intel/oneapi/mpi/2021.1.1/include/gfortran/9.1.0' -I'/opt/intel/oneapi/mpi/2021.1.1/include' -L'/opt/intel/oneapi/mpi/2021.1.1/lib/release' -L'/opt/intel/oneapi/mpi/2021.1.1/lib' -lmpifort -lmpi -lrt -lpthread -ldl --enable-peigs --enable-underscoring --disable-mpi-tests --with-scalapack8=-lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl --with-lapack=-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl --with-blas8=-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl CC=cc CXX=g++ F77=ifort FFLAGS=-fPIC ARMCI_DEFAULT_SHMMAX_UBOUND=131072
```

**Comment by nwchemgit** [comment]
@jeffhammond this pull request is bringing more problems to git: it is triggering github actions that are marked as belonging to your other pull request https://github.com/nwchemgit/nwchem/pull/594
Let's close it for now, hoping that it improves the current messy state of affairs   for the repository.
We can always reopen it at a later time.
I will delete the github actions logs, too

**Pull request closed without merging**
