### PR TITLE
Columbus sonadc 3

### PR DESCRIPTION
**Pull request by lachlanbelcher**
Changes necessary to use NWChem in concert with COLUMBUS

### CODE REVIEW

**Comment by lachlanbelcher** [comment]
Not sure why that one job is taking so long to compile.  When i ran the checks on my fork, it compiled in an hour.
https://github.com/lachlanbelcher/nwchem/actions/runs/4255245112/jobs/7402605300

**Comment by edoapra** [comment]
> Not sure why that one job is taking so long to compile. When i ran the checks on my fork, it compiled in an hour. https://github.com/lachlanbelcher/nwchem/actions/runs/4255245112/jobs/7402605300

Some runners are sometimes slower (HW problems?). I have simply restarted the job.

**Comment by edoapra** [comment]
> > Not sure why that one job is taking so long to compile. When i ran the checks on my fork, it compiled in an hour. https://github.com/lachlanbelcher/nwchem/actions/runs/4255245112/jobs/7402605300
> 
> Some runners are sometimes slower (HW problems?). I have simply restarted the job.

Now the job is progressing at normal speed.

**Comment by edoapra** [comment]
@lachlanbelcher thanks for the contribution and for your patience

**Comment by lachlanbelcher** [comment]
Thanks for the help.  I have this file with some instructions on the new
tasks.

**Comment by edoapra** [comment]
@lachlanbelcher Could you please let me know of what you think of pull request https://github.com/nwchemgit/nwchem/pull/779 ?

**Comment by lachlanbelcher** [comment]
Hi Edoardo,

I will take a look, but I wanted to let you know that I am about done with
branch columbus_sonadc_4, which updates to the latest version of SIFS,
which is required for Columbus 7 (This is the one that uses the "colib"
directory instead of the "sifs" directory)

Lachlan

**Pull request merged**
