### PR TITLE
CCSD(T) TRPDRV OpenACC CUBLAS version

### PR DESCRIPTION
**Pull request by jeffhammond**
at build time, you must specify USE_OPENACC_TRPDRV=1 and NWCHEM_LINK_CUDA=1.
the former turns on the OpenACC+CUBLAS compilation in TRPDRV.
the latter turns on the use of CUDA managed memory in GA.

for now, you must specify DEV_GA=1 at build time, until GlobalArrays/ga#210 is part of GA release version NWChem uses.

at run time, you must specify MA_USE_CUDA_MEM=1
this causes MA to use CUDA managed memory, without which the code will crash, if the OS does not support system unified memory.

this code does not yet deal with how MPI and multi-GPU systems interact.

this only works with NVHPC compilers, because the Fortran interface to CUBLAS requires that.

### CODE REVIEW

**Review by edoapra — COMMENTED** [review]
@jeffhammond I am asking my usual question about preventing code cloning: is there any way to keep a single file with new openacc code inside `ccsd_trpdrv.F`?

**Comment by jeffhammond** [comment]
I prefer separate files per subroutine to allow vimdiff analysis.  I know there is duplication but I've tried to minimize that with fine-grain preprocessing (e.g. in TCE) and the result is incomprehensible.  Having struggled to maintain my own code in `ccsd_t2_8.F`, I've been a lot happier with subroutine duplication.

**Comment by edoapra** [comment]
Unfortunately code cloning quickly becomes a maintainers nightmare, but I can understand you have a different perspective. Anyway, my long struggle against code cloning has always been a loosing battle.

**Comment by edoapra** [comment]
What about use of `OpenACC` vs `OpenMP`? Are you using `OpenACC` features that have no `OpenMP` equivalent?

**Comment by jeffhammond** [comment]
I used OpenACC because this code is NVIDIA-specific because of CUBLAS usage, and our compiler implementation of OpenACC is mature, whereas the OpenMP implementation is still in development.  NVHPC GPU OpenMP works but I've found it is not as fas as OpenACC for NWChem kernels.

OpenACC is a lot easier to use than OpenMP here  because I don't need to specify the data stuff explicitly due to unified memory being used.  OpenMP support for GPU unified memory is not available in any OpenMP compiler I've tried, so I'd have to add a bunch of `is_device_ptr` stuff.

**Comment by jeffhammond** [comment]
I feel your pain on the code duplication issue and am interested in converging everything at some point.  One of the issues is that I need Fortran allocatable to get GPU unified memory without source changes.  If you are willing to deprecate MA in favor of Fortran allocatable, if only in TRPDRV, then I can consolidate some of the code.

**Comment by edoapra** [comment]
The only thing that is preventing to abandon MA for F90 (and later) dynamical memory allocation is to implement a mechanism that keeps track of the allocated memory

**Comment by edoapra** [comment]
CCSD QA tests are failing in  github actions.
https://github.com/nwchemgit/nwchem/runs/2587837861?check_suite_focus=true
This is the tail of the output file
```
task       631 out of       630 done 100%  at      22.8 secs
 aoccsd: trpdrv_openacc disabled 
```

**Comment by jeffhammond** [comment]
@edoapra I fixed that bug.

**Comment by hjjvandam** [comment]
That seems like a solvable problem depending on how fancy the interface should be.

  *   We could have an allocator routine that checks how much MA memory has been allocated, what the upper memory limit is, and how much the current allocation would add to the memory usage. Then it can either allocate the memory or fail.
  *   The free routine could check the size of allocated Fortran array (there is a SIZE function for that), so we can account for the amount of memory freed.
  *   The number of subroutines in the interface is the main issue I guess. The Global Arrays support up to 7 dimensions. It would be nice to have an interface that supports not just the size for each dimension but also a lower and upper limit for each dimension. This gets you to 14 subroutines per data type. You want at least double, double complex, and integer allocators so that is another factor of 3. So in total one would have to implement at least 42 allocator routines.
  *   The other question is: would you want this thing to be a module or just a collection Fortran subroutines. A module would require changes to how NWChem builds, whereas the other approach would just require an interface specification and could be handled as a regular include file.
Did I miss anything? I guess checking the memory usage from a GPU could be tricky (the amount of memory allocated through MA might not mean much in that case). Would such a little library have to support memory allocation on a device?

**Pull request merged**
