### PR TITLE
apply MacOS header fix

### PR DESCRIPTION
**Pull request by jeffhammond**
https://github.com/GlobalArrays/ga/pull/162 has details

Signed-off-by: Hammond, Jeff R <jeff.r.hammond@intel.com>

### CODE REVIEW

**Comment by edoapra** [comment]
@jeffhammond are you still experiencing this issue? I am using to macs with (ouch!) Catalina macOS and Xcode 11.6, but I still have to stumble into this error

**Comment by jeffhammond** [comment]
I confess that I haven't compiled NWChem on my laptop in a while so I don't know.  I'll try to test again soon.  However, the issue here is widely reported on the internet and at the same time, no one understands where it occurs, since it affects users with identical versions of MacOS and XCode differently.  Since it cannot change the behavior of a program in the absence of the bug, I think it's innocuous to apply it anyways.

**Comment by edoapra** [comment]
Fine for me too. We need to merge the makefile bits for MACX64 into the LINUX64 target since they share lots of bits. I can see that GNU and Clang compilers have a builtin define __APPLE__ that should probably be used instead of MACX. Do you have any idea if ifort has the builtin define __APPLE__, too?

**Comment by jeffhammond** [comment]
I will look later. I suspect the macros are defined in headers not by compiler and ICC uses system headers.

**Pull request merged**
