### PR TITLE
Super heavy elements

### PR DESCRIPTION
**Pull request by jeffhammond**
this addresses https://github.com/nwchemgit/nwchem/issues/821.

i added elements up to 118 (https://en.wikipedia.org/wiki/Oganesson) but stopped there because i cannot add 119 aka Ununennium aka Uue without adding support for elements with 3 charactar symbols.

~i refactored 4 data tables into `geomP.fh` to eliminate code duplication.~ i added a new header, `periodic.fh`, to eliminate code duplication.

### CODE REVIEW

**Comment by miroi** [comment]
Hello,

thanks for this PR; btw what about shortening element names of 119,, 120 ?  119 = Uu, 120 = Ub ? 

Also there is error in the code :
"/usr/bin/ld: /home/runner/work/nwchem/nwchem/lib/LINUX64/libccsd.a(ccsd_aux.o):(.data+0x0): multiple definition of `celements_'; /home/runner/work/nwchem/nwchem/lib/LINUX64/libnwctask.a(task_bsse.o):(.data+0x0): first defined here"

**Comment by jeffhammond** [comment]
> thanks for this PR; btw what about shortening element names of 119,, 120 ? 119 = Uu, 120 = Ub ?

"Uu" obviously doesn't work because all elements with Z>118 currently start with "Uu".

We should figure out the situation up to Z=118 first.  Once that is solved, we can discuss how to deal with 3-character element symbols.  The solution likely requires changes to the parser, which aren't impossible, but should be done separately.

For example, we can add a branch for symbols that start with "Uu" and then look at the next character when that matches, which might be simpler than doing a wholesale change to 3-character symbols everywhere.

> Also there is error in the code : "/usr/bin/ld: /home/runner/work/nwchem/nwchem/lib/LINUX64/libccsd.a(ccsd_aux.o):(.data+0x0): multiple definition of `celements_'; /home/runner/work/nwchem/nwchem/lib/LINUX64/libnwctask.a(task_bsse.o):(.data+0x0): first defined here"

Please copy geomP.fh from src/geom to src/include.  It is likely that you have the old copy of geomP.fh in src/include, due to how the build system works.

**Comment by jeffhammond** [comment]
Sorry, I think I need to rename `celements`.  Please stand by for an update.

**Comment by jeffhammond** [comment]
It should be fixed now.  I don't understand common block includes but I just added a new header.

**Comment by jeffhammond** [comment]
@edoapra All the CI jobs are failing, but I wonder if it is related to the cache.  Can you help me figure this out?

**Comment by miroi** [comment]
This error : "make[1]: *** No rule to make target '/home/runner/work/nwchem/nwchem/src/include/geomP.fh', needed by '/home/runner/work/nwchem/nwchem/lib/LINUX64/libnwcutil.a(basis.o)'.  Stop." ...

**Comment by jeffhammond** [comment]
Yeah, I don't understand that error. It doesn't appear locally when I build and test.

**Comment by jeffhammond** [comment]
I have no caches on my fork.

**Comment by edoapra** [comment]
> I have no caches on my fork.

https://github.com/jeffhammond/nwchem/actions/caches

**Comment by edoapra** [comment]
This is the error
```
2023-07-10T08:25:22.1418081Z make[1]: *** No rule to make target '/home/runner/work/nwchem/nwchem/src/include/geomP.fh', needed by '/home/runner/work/nwchem/nwchem/lib/LINUX64/libnwcutil.a(basis.o)'.  Stop.
2023-07-10T08:25:22.1419071Z make[1]: Leaving directory '/home/runner/work/nwchem/nwchem/src/basis'
```

**Comment by edoapra** [comment]
periodic.fh does not seem to be present

**Comment by edoapra** [comment]
The update step for the include files in the geom directory fails since periodic.fh is not present. This results in geomp.fh not being copied to $NWCHEM_TOP/src/include

**Review by edoapra — CHANGES_REQUESTED** [review]
periodic.fh was not checked in as part of this commit

**Comment by jeffhammond** [comment]
Sorry, I forgot to `git add` the new file.  It should be okay now.

**Review by edoapra — COMMENTED** [review]
What about moving the definition and setting of `nelements` from `geomP.fh` to `periodic.fh`?
After this change, you could use `periodic.fh` without having to include geomP.fh first.

**Review by edoapra — APPROVED** [review]

**Comment by edoapra** [comment]
I pushed some changes to address the nvfortran failure in $NWCHEM_TOP/src/geom

https://github.com/nwchemgit/nwchem/actions/runs/5511093015/jobs/10046185487?pr=822

**Comment by jeffhammond** [comment]
> What about moving the definition and setting of `nelements` from `geomP.fh` to `periodic.fh`? After this change, you could use `periodic.fh` without having to include geomP.fh first.

Works for me.  I created periodic.fh because of some duplicate symbol errors when I added `common/celements/` to geomP.fh.  I do not understand common block headers so well, unfortunately.

**Comment by jeffhammond** [comment]
> I pushed some changes to address the nvfortran failure in $NWCHEM_TOP/src/geom
> 
> https://github.com/nwchemgit/nwchem/actions/runs/5511093015/jobs/10046185487?pr=822

I didn't test with nvfortran but I'll reproduce and file the bug.

**Comment by jeffhammond** [comment]
I do not see the crash with 23.1 so either it is new in 23.3, or it is specific to the flags used in CI.

I am downloading 23.3 now.

```
jhammond@nuclear:~/NWChem/github/src/geom$ make geom.o && echo OK
nvfortran -i8 -g -Mdalign -Kieee -Mllalign -Mbackslash -Mcache_align   -tp host -Mnorecursive -g -O2    -I. -I/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/hpcx/hpcx-2.13/ompi/include -I/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/hpcx/hpcx-2.13/ompi/lib -I/home/jhammond/NWChem/github/src/include -I/home/jhammond/NWChem/github/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DPARALLEL_DIAG -DUSE_F90_ALLOCATABLE -DOPENBLAS -DUSE_INTEGER8  -c -o geom.o geom.F
OK
jhammond@nuclear:~/NWChem/github/src/geom$ nvfortran -v
Export NVCOMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/23.1
Export PGI=/opt/nvidia/hpc_sdk
nvfortran-Warning-No files to process
```

**Comment by edoapra** [comment]
Yes, Github Actions use nvfortran 23.3.  
Anyhow, getting rid of a common block that was not needed did the trick.

I am going to merge this pull request soon.  We could have the changes for 119-120 in a separate pull request.

**Comment by jeffhammond** [comment]
Agree on Z=>119.  I will see if I can work out an easy fix to the parser for "UU*" cases.

**Comment by miroi** [comment]
Thanks for the merge ! I switch to master branch to profit from this new feature. Do not forget to advertise it - SHEs are emerging field, with relativistic quantum chemistry helping experimentalists.

**Comment by jeffhammond** [comment]
I can't reproduce the nvfortran crash.  I wonder if CI runs in a memory-constrained environment.

```
jehammond@gorby:/local/jehammond/NWCHEM/github/src/geom$ nvfortran geom.F -tp host -c -i8 -Mdalign -Kieee -Mllalign -Mbackslash -Mcache_align -Mnorecursive -g -O2 -Mvect=simd -Mno-signed-zeros -I. -I/usr/include/x86_64-linux-gnu/mpich -I/usr/include/x86_64-linux-gnu/mpich -I$NWCHEM_TOP/src/include -I$NWCHEM_TOP/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DUSE_OPENMP -DSCALAPACK -DNOIO -DEAFHACK -DPARALLEL_DIAG -DOPENBLAS -DOPENBLAS -DUSE_INTEGER8
jehammond@gorby:/local/jehammond/NWCHEM/github/src/geom$ nvfortran geom.F -tp skylake-avx512 -c -i8 -Mdalign -Kieee -Mllalign -Mbackslash -Mcache_align -Mnorecursive -g -O2 -Mvect=simd -Mno-signed-zeros -I. -I/usr/include/x86_64-linux-gnu/mpich -I/usr/include/x86_64-linux-gnu/mpich -I$NWCHEM_TOP/src/include -I$NWCHEM_TOP/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DUSE_OPENMP -DSCALAPACK -DNOIO -DEAFHACK -DPARALLEL_DIAG -DOPENBLAS -DOPENBLAS -DUSE_INTEGER8
jehammond@gorby:/local/jehammond/NWCHEM/github/src/geom$ nvfortran -v
Export NVCOMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/23.3
Export PGI=/opt/nvidia/hpc_sdk
nvfortran-Warning-No files to process
```

**Comment by edoapra** [comment]
> I can't reproduce the nvfortran crash. I wonder if CI runs in a memory-constrained environment.
> 
> ```
> jehammond@gorby:/local/jehammond/NWCHEM/github/src/geom$ nvfortran geom.F -tp host -c -i8 -Mdalign -Kieee -Mllalign -Mbackslash -Mcache_align -Mnorecursive -g -O2 -Mvect=simd -Mno-signed-zeros -I. -I/usr/include/x86_64-linux-gnu/mpich -I/usr/include/x86_64-linux-gnu/mpich -I$NWCHEM_TOP/src/include -I$NWCHEM_TOP/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DUSE_OPENMP -DSCALAPACK -DNOIO -DEAFHACK -DPARALLEL_DIAG -DOPENBLAS -DOPENBLAS -DUSE_INTEGER8
> jehammond@gorby:/local/jehammond/NWCHEM/github/src/geom$ nvfortran geom.F -tp skylake-avx512 -c -i8 -Mdalign -Kieee -Mllalign -Mbackslash -Mcache_align -Mnorecursive -g -O2 -Mvect=simd -Mno-signed-zeros -I. -I/usr/include/x86_64-linux-gnu/mpich -I/usr/include/x86_64-linux-gnu/mpich -I$NWCHEM_TOP/src/include -I$NWCHEM_TOP/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DUSE_OPENMP -DSCALAPACK -DNOIO -DEAFHACK -DPARALLEL_DIAG -DOPENBLAS -DOPENBLAS -DUSE_INTEGER8
> jehammond@gorby:/local/jehammond/NWCHEM/github/src/geom$ nvfortran -v
> Export NVCOMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/23.3
> Export PGI=/opt/nvidia/hpc_sdk
> nvfortran-Warning-No files to process
> ```

You seem to be using 23.3 and not 23.5

**Comment by edoapra** [comment]
[geom_nvcrash.f.txt](https://github.com/nwchemgit/nwchem/files/12021352/geom_nvcrash.f.txt)
(had to rename geom_nvcrash.f to geom_nvcrash.f.txt to get it uploaded)  
```
$ nvfortran  -c geom_nvcrash.f 
nvfortran-Fatal-/data/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/compilers/bin/tools/fort2 TERMINATED by signal 11
Arguments to /data/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/compilers/bin/tools/fort2
/data/opt/nvidia/hpc_sdk/Linux_x86_64/23.5/compilers/bin/tools/fort2 /tmp/nvfortran6xt-UyAxb8st.ilm -fn geom_nvcrash.f -opt 1 -terse 1 -inform warn -x 51 0x20 -x 119 0xa10000 -x 122 0x40 -x 123 0x1000 -x 127 4 -x 127 17 -x 19 0x400000 -x 28 0x40000 -x 120 0x10000000 -x 70 0x8000 -x 122 1 -x 125 0x20000 -quad -x 59 4 -tp skylake-avx512 -x 120 0x1000 -x 124 0x1400 -y 15 2 -x 57 0x3b0000 -x 58 0x48000000 -x 49 0x100 -astype 0 -x 121 1 -x 183 4 -x 121 0x800 -x 68 0x1 -x 8 0x40000000 -x 70 0x40000000 -x 56 0x10 -x 54 0x10 -x 249 160 -x 68 0x20 -x 70 0x40000000 -x 8 0x40000000 -x 164 0x800000 -x 71 0x2000 -x 71 0x4000 -x 34 0x40000000 -x 83 0x1 -x 85 0x1 -x 206 0x02 -x 120 0x1000000 -x 73 0x04 -x 68 0x1 -x 39 4 -x 56 0x10 -x 26 0x10 -x 26 1 -x 56 0x4000 -x 124 1 -x 197 0 -x 175 0 -x 203 0 -x 204 0 -y 163 0xc0000000 -x 189 0x10 -y 189 0x4000000 -x 60 512 -cci /tmp/nvfortrankxt-EETxETvS.cci -cmdline '+nvfortran geom_nvcrash.f -c' -stbfile /tmp/nvfortranAxt-oszcQawO.stb -asm /tmp/nvfortranAxt-oTew8htx.ll
```

**Comment by jeffhammond** [comment]
@edoapra FYI the compiler team says that initiating a COMMON block more than once is illegal, although it works in GCC and Intel Fortran.  The correct method for such initializations, which NWChem uses, is a `BLOCK DATA` procedure.  So the error here was mine, not the compiler.  I don't think the incorrect usage exists elsewhere in NWChem.

**Pull request merged**
