### PR TITLE
globally replace DFLOAT() with DBLE()

### LINKED ISSUE #210: dfloat -> dble
Many Office of Science codes use dfloat(n) where n is some integer to convert to double precision. Unfortunately, this is not a standard Fortran intrinsic procedure. It appears to be some extension that is supported by GCC and Intel (which probably covers well over 80% of the everyday Fortran compiler usage)

The correct way to do this is using dble(n). More info here:
https://github.com/flang-compiler/f18/issues/1077

I grepped through the NWChem source code and there way too many places where dfloat is used, e.g. TCE, DFT, etc., to fix this manually. Maybe there is some macro magic that can handle this or I can push the Flang developers to implement it, but it will probably end up low on their priority list.

I don't expect you guys to switch over to dble(n), but mostly making you aware of the issue. But if you do want to switch over, I am willing to make the PR for it :)

### PR DESCRIPTION
**Pull request by jeffhammond**
Resolves #210, assuming it is correct. Testing still in progress.

### CODE REVIEW

**Comment by jeffhammond** [comment]
Yes, please wait.  I want to do a local build and QA run.

**Comment by jeffhammond** [comment]
Clean build with IFX for MODULES=smallqm (because NWPW includes FEFF and FEFF doesn't compile with IFX because of disgusting GOTO statements).

**Comment by naromero77** [comment]
I think it has to be working with `f18`, simply because I got past the file that was giving me trouble. However, `f18` is now stuck on another issue, unrelated to `dfloat()`, so I cannot real confirm it.

If it passess travis-ci and your local tests, I would recommend just merging it in.

**Comment by edoapra** [comment]
Decide to merge since I had another large number of changes for f18

**Pull request merged**
