### PR TITLE
Parallel string implementation

### PR DESCRIPTION
**Pull request by hjjvandam**
This pull request adds a parallel implementation of the string method. In the parallel mode of execution all beads along the string are executed at the same time, each in its own processor subgroup. This requires that the job has at least one processor per bead. If not enough processors are available the calculation automatically falls back to the serial implementation. To explicitly specify the mode of execution a new keyword has been added to the string input block
```
   mode serial    # execute beads one after another
   mode parallel  # execute all beads at the same time
```
Assumptions:

- All files reside on a shared file system so all nodes can see all file
- Load balancing the calculations across the beads is acceptably good
- It is preferred to keep the serial mode of execution the default setting. Because the molecule sizes may differ significantly a user has to determine how many cores are needed to execute a single bead

### CODE REVIEW

**Comment by edoapra** [comment]
@hjjvandam please rebase your fork since it is 64 commits behind the current master

**Comment by edoapra** [comment]
@hjjvandam please provide QA test input and output files that follow the following convention:  
in a directory named `test1`, only the input file `test1.nw` and `test1.out` should be present

**Comment by edoapra** [comment]
@hjjvandam you have performed a merge not a rebase

**Comment by hjjvandam** [comment]
Hmmm, git seems totally confused now. I'll update the master on my fork, create a new branch, copy my changes over, push that, and create a new pull request.

**Pull request closed without merging**
